import Link from "next/link";
import { Zap, ShieldCheck, Cpu, Code2, Database, Sparkles, ArrowRight, Layers } from "lucide-react";
import { MarketingNavbar } from "@/components/marketing/marketing-navbar";
import { MarketingFooter } from "@/components/marketing/marketing-footer";

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#0B1020] text-slate-100 font-sans">
      <MarketingNavbar />

      <main className="max-w-5xl mx-auto px-6 py-20 space-y-16">
        {/* Story Header */}
        <div className="space-y-4 text-center max-w-2xl mx-auto">
          <span className="text-xs font-bold text-[#D4FF32] uppercase tracking-wider">About SocialPilot AI</span>
          <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
            Create Once. Publish Everywhere. Manage Everything.
          </h1>
          <p className="text-sm text-slate-400 leading-relaxed">
            We built SocialPilot AI because modern social growth shouldn&apos;t require spending 15+ hours weekly copying text between disconnected browser tabs.
          </p>
        </div>

        {/* Vision & Mission */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="p-8 rounded-3xl bg-[#121A2B] border border-[rgba(255,255,255,0.08)] space-y-3">
            <div className="w-10 h-10 rounded-xl bg-[#D4FF32]/10 text-[#D4FF32] flex items-center justify-center">
              <Zap className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-white">Our Mission</h2>
            <p className="text-xs text-slate-300 leading-relaxed">
              To empower agencies, creators, and modern brands with a unified social intelligence platform that combines the multi-channel distribution of Buffer, Canva&apos;s visual agility, and ChatGPT&apos;s native adaptation intelligence into a single coherent operating system.
            </p>
          </div>

          <div className="p-8 rounded-3xl bg-[#121A2B] border border-[rgba(255,255,255,0.08)] space-y-3">
            <div className="w-10 h-10 rounded-xl bg-[#C4B5FD]/10 text-[#C4B5FD] flex items-center justify-center">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-white">Our Standards</h2>
            <p className="text-xs text-slate-300 leading-relaxed">
              We reject lazy cross-posting and black-box automation that damages brand reputation. Every output generated by SocialPilot is filtered through strict Brand Brain guidelines, ensuring negative claims are blocked and channel syntax is respected.
            </p>
          </div>
        </div>

        {/* Engineering Principles */}
        <div className="space-y-6">
          <div className="text-center space-y-2">
            <h2 className="text-2xl font-bold text-white">Engineering Architecture</h2>
            <p className="text-xs text-slate-400">Architected for enterprise security and distributed scalability.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-xs text-slate-300">
            <div className="p-6 rounded-2xl bg-[#121A2B] border border-[rgba(255,255,255,0.08)] space-y-2.5">
              <div className="flex items-center gap-2 text-white font-bold text-sm">
                <Database className="w-4 h-4 text-[#D4FF32]" />
                <span>Prisma + PostgreSQL</span>
              </div>
              <p className="text-slate-400 leading-relaxed">
                Relational schema enforcing strict workspace isolation. Every brand, draft, asset, and comment references an immutable tenant key.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-[#121A2B] border border-[rgba(255,255,255,0.08)] space-y-2.5">
              <div className="flex items-center gap-2 text-white font-bold text-sm">
                <ShieldCheck className="w-4 h-4 text-[#C4B5FD]" />
                <span>AES-256-GCM Encryption</span>
              </div>
              <p className="text-slate-400 leading-relaxed">
                OAuth access tokens and secrets are encrypted with randomized 12-byte IVs and 16-byte authentication tags to prevent key tampering.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-[#121A2B] border border-[rgba(255,255,255,0.08)] space-y-2.5">
              <div className="flex items-center gap-2 text-white font-bold text-sm">
                <Layers className="w-4 h-4 text-emerald-400" />
                <span>Idempotent Worker Queue</span>
              </div>
              <p className="text-slate-400 leading-relaxed">
                Deterministic SHA-256 idempotency hashing with distributed lease locking ensures scheduled posts never double-publish.
              </p>
            </div>
          </div>
        </div>

        {/* CTA */}
        <div className="p-10 rounded-3xl bg-[#182238] border border-[#D4FF32]/30 text-center space-y-5">
          <h2 className="text-2xl font-bold text-white">Join the Next Generation of Social Management</h2>
          <p className="text-xs text-slate-300 max-w-md mx-auto">
            Test SocialPilot AI in live Demo Mode today and see how our unified intelligence transforms your workflow.
          </p>
          <Link
            href="/register"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl bg-[#D4FF32] text-[#0B1020] font-bold text-xs hover:bg-[#C2ED25] transition-all"
          >
            <span>Create Free Workspace</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}
